<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page import="java.util.*"%><%@page import="com.DB.DBConnect"%><%@page import="com.dao.JobDAO"%><%@page import="com.dao.UserDAO"%><%@page import="com.dao.ApplicationDAO"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ page isELIgnored="false"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Admin Dashboard | Job Portal</title><%@include file="all_component/all_css.jsp"%></head><body>
<c:if test="${userobj.role ne 'admin'}"><c:redirect url="login.jsp"></c:redirect></c:if><%@include file="all_component/navbar.jsp"%>
<% JobDAO jd=new JobDAO(DBConnect.getconn()); UserDAO ud=new UserDAO(DBConnect.getconn()); ApplicationDAO ad=new ApplicationDAO(DBConnect.getconn()); List<ApplicationDAO.ApplicationRecord> applications=ad.getAllApplications(); %>
<div class="page-header"><div class="container"><div class="section-kicker">Administration</div><h1>Portal overview</h1><p>Manage job listings and review candidate applications from one place.</p></div></div>
<main class="container section-space pt-4">
<c:if test="${not empty succMsg}"><div class="alert alert-success border-0 shadow-sm"><i class="fa-solid fa-circle-check me-2"></i>${succMsg}</div><c:remove var="succMsg"/></c:if>
<div class="row g-3 mb-5"><div class="col-sm-6 col-lg-3"><div class="dashboard-stat"><div class="icon"><i class="fa-solid fa-users"></i></div><div class="number"><%=ud.countUsers()%></div><div class="caption">Registered users</div></div></div><div class="col-sm-6 col-lg-3"><div class="dashboard-stat"><div class="icon"><i class="fa-solid fa-briefcase"></i></div><div class="number"><%=jd.countJobs()%></div><div class="caption">Total jobs</div></div></div><div class="col-sm-6 col-lg-3"><div class="dashboard-stat"><div class="icon"><i class="fa-solid fa-circle-check"></i></div><div class="number"><%=jd.countActiveJobs()%></div><div class="caption">Active jobs</div></div></div><div class="col-sm-6 col-lg-3"><div class="dashboard-stat"><div class="icon"><i class="fa-solid fa-paper-plane"></i></div><div class="number"><%=ad.countApplications()%></div><div class="caption">Applications</div></div></div></div>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><div class="section-kicker">Quick actions</div><h2 class="h4 section-title mb-0 mt-1">Job management</h2></div><div class="d-flex gap-2"><a href="add_job.jsp" class="btn btn-jp-primary"><i class="fa-solid fa-plus me-1"></i>Post a Job</a><a href="view_job.jsp" class="btn btn-jp-secondary"><i class="fa-solid fa-list-check me-1"></i>Manage Jobs</a></div></div>
<div id="applications" class="mt-5"><div class="section-kicker">Candidate activity</div><h2 class="h4 section-title mb-3 mt-1">Recent applications</h2><% if(applications.isEmpty()){ %><div class="empty-state">No applications have been submitted yet.</div><% } else { %><div class="admin-table-wrap"><table class="table admin-table"><thead><tr><th>Candidate</th><th>Job</th><th>Applied</th><th>Status</th><th>Update</th></tr></thead><tbody><% int limit=0; for(ApplicationDAO.ApplicationRecord a:applications){ if(limit++>=20) break; %><tr><td><strong><%=a.userName%></strong><br><span class="small text-muted"><%=a.userEmail%></span></td><td><%=a.jobTitle%></td><td><%=a.appliedAt%></td><td><span class="application-status"><%=a.status%></span></td><td><form action="update_application" method="post" class="d-flex gap-2"><input type="hidden" name="id" value="<%=a.id%>"><select name="status" class="form-select form-select-sm"><option <%= "Applied".equals(a.status)?"selected":"" %>>Applied</option><option <%= "Under Review".equals(a.status)?"selected":"" %>>Under Review</option><option <%= "Shortlisted".equals(a.status)?"selected":"" %>>Shortlisted</option><option <%= "Interview".equals(a.status)?"selected":"" %>>Interview</option><option <%= "Selected".equals(a.status)?"selected":"" %>>Selected</option><option <%= "Rejected".equals(a.status)?"selected":"" %>>Rejected</option></select><button class="btn btn-sm btn-jp-secondary">Save</button></form></td></tr><% } %></tbody></table></div><% } %></div>
</main><%@include file="all_component/footer.jsp"%></body></html>
