<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page import="java.util.*"%><%@page import="com.entity.User"%><%@page import="com.entity.Jobs"%><%@page import="com.DB.DBConnect"%><%@page import="com.dao.SavedJobDAO"%><%@page import="com.dao.ApplicationDAO"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ page isELIgnored="false"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>My Dashboard | Job Portal</title><%@include file="all_component/all_css.jsp"%></head><body>
<c:if test="${empty userobj or userobj.role ne 'user'}"><c:redirect url="login.jsp"></c:redirect></c:if><%@include file="all_component/navbar.jsp"%>
<% User u=(User)session.getAttribute("userobj"); SavedJobDAO savedDao=new SavedJobDAO(DBConnect.getconn()); ApplicationDAO appDao=new ApplicationDAO(DBConnect.getconn()); List<Jobs> savedJobs=savedDao.getSavedJobs(u.getId()); List<ApplicationDAO.ApplicationRecord> apps=appDao.getApplicationsForUser(u.getId()); %>
<div class="page-header"><div class="container"><div class="section-kicker">Your account</div><h1>Welcome back, <%=u.getName()%>.</h1><p>Manage saved jobs and keep track of the applications you've submitted.</p></div></div>
<main class="container section-space pt-4">
<c:if test="${not empty succMsg}"><div class="alert alert-success border-0 shadow-sm"><i class="fa-solid fa-circle-check me-2"></i>${succMsg}</div><c:remove var="succMsg"/></c:if>
<div class="row g-3 mb-5"><div class="col-md-4"><div class="dashboard-stat"><div class="icon"><i class="fa-solid fa-paper-plane"></i></div><div class="number"><%=apps.size()%></div><div class="caption">Applications submitted</div></div></div><div class="col-md-4"><div class="dashboard-stat"><div class="icon"><i class="fa-solid fa-bookmark"></i></div><div class="number"><%=savedJobs.size()%></div><div class="caption">Saved jobs</div></div></div><div class="col-md-4"><div class="dashboard-stat"><div class="icon"><i class="fa-solid fa-user-check"></i></div><div class="number"><%=u.getQualification()%></div><div class="caption">Current qualification</div></div></div></div>
<div class="row g-4"><div class="col-lg-7"><div class="d-flex justify-content-between align-items-end mb-3"><div><div class="section-kicker">Applications</div><h2 class="h4 section-title mb-0 mt-1">My applications</h2></div></div>
<% if(apps.isEmpty()) { %><div class="empty-state"><i class="fa-regular fa-file-lines d-block"></i><h3 class="h5" style="color:var(--jp-navy)">No applications yet</h3><p class="mb-3">Find a role that fits you and apply from its details page.</p><a href="home.jsp" class="btn btn-jp-primary">Find Jobs</a></div><% } else { %><div class="d-grid gap-2"><% for(ApplicationDAO.ApplicationRecord a:apps){ String cls=""; if("Rejected".equalsIgnoreCase(a.status))cls="rejected"; else if("Interview".equalsIgnoreCase(a.status))cls="interview"; else if("Selected".equalsIgnoreCase(a.status))cls="selected"; %><div class="application-row"><div class="d-flex justify-content-between gap-3"><div><h3 class="h6 mb-1" style="color:var(--jp-navy)"><%=a.jobTitle%></h3><div class="small muted-text"><%=a.location%> · <%=a.category%></div><div class="small muted-text mt-2">Applied <%=a.appliedAt%></div></div><span class="application-status <%=cls%>"><%=a.status%></span></div><div class="mt-3"><a href="one_view.jsp?id=<%=a.jobId%>" class="btn btn-sm btn-jp-secondary">View Job</a></div></div><% } %></div><% } %></div>
<div class="col-lg-5"><div class="d-flex justify-content-between align-items-end mb-3"><div><div class="section-kicker">Saved</div><h2 class="h4 section-title mb-0 mt-1">Saved jobs</h2></div></div><% if(savedJobs.isEmpty()){ %><div class="empty-state"><i class="fa-regular fa-bookmark d-block"></i><h3 class="h5" style="color:var(--jp-navy)">Nothing saved yet</h3><p class="mb-3">Use Save Job on any listing you want to revisit.</p><a href="home.jsp" class="btn btn-jp-secondary">Browse Jobs</a></div><% } else { %><div class="d-grid gap-2"><% for(Jobs j:savedJobs){ %><div class="application-row"><h3 class="h6 mb-1" style="color:var(--jp-navy)"><%=j.getTitle()%></h3><div class="small muted-text"><i class="fa-solid fa-location-dot me-1"></i><%=j.getLocation()%> · <%=j.getCategory()%></div><div class="mt-3"><a href="one_view.jsp?id=<%=j.getId()%>" class="btn btn-sm btn-jp-secondary">Open Job</a></div></div><% } %></div><% } %></div></div>
</main><%@include file="all_component/footer.jsp"%></body></html>
