<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page import="java.util.*"%><%@page import="com.entity.Jobs"%><%@page import="com.DB.DBConnect"%><%@page import="com.dao.JobDAO"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ page isELIgnored="false"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Search Results | Job Portal</title><%@include file="all_component/all_css.jsp"%></head><body>
<c:if test="${empty userobj}"><c:redirect url="login.jsp"></c:redirect></c:if><%@include file="all_component/navbar.jsp"%>
<div class="page-header"><div class="container"><div class="section-kicker">Search results</div><h1>Jobs matching your filters</h1><p>Review the available roles and open any listing for the full description.</p></div></div>
<main class="container section-space pt-4"><%
String loc=request.getParameter("loc"); String cat=request.getParameter("cat"); if(loc==null||loc.trim().isEmpty())loc="lo"; if(cat==null||cat.trim().isEmpty())cat="ca";
JobDAO dao=new JobDAO(DBConnect.getconn()); List<Jobs> list;
if("lo".equals(loc)&&"ca".equals(cat)) list=dao.getAllJobs(); else if("lo".equals(loc)||"ca".equals(cat)) list=dao.getJobsORLocationAndCate("ca".equals(cat)?"":cat,"lo".equals(loc)?"":loc); else list=dao.getJobsAndLocationAndCate(cat,loc);
%><div class="d-flex justify-content-between align-items-center mb-3"><div class="small muted-text">Showing <strong><%=list.size()%></strong> result(s)</div><a href="home.jsp" class="btn btn-sm btn-jp-secondary"><i class="fa-solid fa-arrow-left me-1"></i> Back to Search</a></div>
<% if(list.isEmpty()){ %><div class="empty-state"><i class="fa-regular fa-face-frown d-block"></i><h3 class="h5" style="color:var(--jp-navy)">No matching jobs</h3><p class="mb-3">Try a different location or category.</p><a href="home.jsp" class="btn btn-jp-primary">Change Filters</a></div><% } else { %>
<div class="d-grid gap-3"><% for(Jobs j:list){ String d=j.getDescription()==null?"":j.getDescription(); String preview=d.length()>120?d.substring(0,120)+"...":d; String status=j.getStatus()==null?"":j.getStatus(); %><div class="job-card"><div class="job-card-head"><div><h3 class="job-title"><%=j.getTitle()%></h3><div class="job-date mt-1">Posted <%=j.getPdate()%></div></div><div class="d-flex align-items-center gap-2"><span class="status-badge <%= "Inactive".equalsIgnoreCase(status)?"inactive":"" %>"><%=status%></span><a class="save-btn" href="one_view.jsp?id=<%=j.getId()%>" title="Open job"><i class="fa-regular fa-bookmark"></i></a></div></div><p class="job-description"><%=preview%></p><div class="job-meta"><span class="meta-chip"><i class="fa-solid fa-location-dot"></i><%=j.getLocation()%></span><span class="meta-chip"><i class="fa-solid fa-layer-group"></i><%=j.getCategory()%></span></div><div class="job-actions"><span class="small muted-text">Job ID #<%=j.getId()%></span><a href="one_view.jsp?id=<%=j.getId()%>" class="btn btn-sm btn-jp-secondary px-3">View Details <i class="fa-solid fa-arrow-right ms-1"></i></a></div></div><% } %></div><% } %></main><%@include file="all_component/footer.jsp"%></body></html>
